FROM golang:1.26-alpine AS builder

ARG TARGETOS
ARG TARGETARCH
# Version stamp flags, generated by buildscripts/gen-ldflags.go in CI.
# Local `docker build .` produces a DEVELOPMENT-stamped binary.
ARG LDFLAGS="-s -w"

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -tags kqueue -trimpath -ldflags "${LDFLAGS}" -o /openbucket .

FROM alpine:3.21

# bash and GNU coreutils match the userland of the upstream MinIO images;
# operational tooling (and our resiliency test suite) execs GNU-style
# commands and bash syntax inside the container.
RUN apk add --no-cache ca-certificates bash coreutils && \
    ln -sf /bin/bash /bin/sh && \
    mkdir -p /data

COPY --from=builder /openbucket /usr/bin/openbucket
# Compatibility name for tooling and commands that still invoke `minio`.
RUN ln -s /usr/bin/openbucket /usr/bin/minio

COPY dockerscripts/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh

EXPOSE 9000 9001

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]

VOLUME ["/data"]

CMD ["openbucket"]
