// Code generated by "stringer -type=rebalStatus -trimprefix=rebal erasure-server-pool-rebalance.go"; DO NOT EDIT.

package cmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[rebalNone-0]
	_ = x[rebalStarted-1]
	_ = x[rebalCompleted-2]
	_ = x[rebalStopped-3]
	_ = x[rebalFailed-4]
}

const _rebalStatus_name = "NoneStartedCompletedStoppedFailed"

var _rebalStatus_index = [...]uint8{0, 4, 11, 20, 27, 33}

func (i rebalStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_rebalStatus_index)-1 {
		return "rebalStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _rebalStatus_name[_rebalStatus_index[idx]:_rebalStatus_index[idx+1]]
}
